import { type NextPage } from "next";
import Head from "next/head";

const SinglePost: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          Single Post
        </div>
      </main>
    </>
  );
};

export default SinglePost;
